const store=require('../../../services/store')
const cloud=require('../../../services/collaboration')
Page({data:{id:'',chapter:null,moments:[],limit:12,hasMore:false,filter:'all',calendar:null,showCalendar:false,coverFailed:false,missing:false,activeTab:'瞬间',tabs:['瞬间','日历','目标','成员','回望'],goalPanel:false,goalTitle:'',goalId:'',goalError:''},onLoad(options){this.setData({id:options.id||''});this.load();cloud.pullChapter(this.data.id).then(()=>this.load())},onShow(){if(this.data.id)this.load()},load(){const chapter=store.getChapter(this.data.id);if(!chapter)return this.setData({chapter:null,missing:true});const all=store.getMoments(chapter.id,this.data.filter);const current=this.data.calendar;const calendar=store.getCalendarData(this.data.id,current&&current.monthKey,current&&current.selectedDateKey);const review=store.getReviewData(this.data.id);this.setData({chapter,moments:all.slice(0,this.data.limit),hasMore:all.length>this.data.limit,calendar,reviewPhotos:review?review.photos:[],missing:false})},onReachBottom(){if(this.data.activeTab==='瞬间'&&this.data.hasMore){this.setData({limit:this.data.limit+12});this.load()}},onPullDownRefresh(){cloud.pullChapter(this.data.id).finally(()=>{this.load();wx.stopPullDownRefresh()})},openMoment(e){const id=e.detail.id||e.currentTarget.dataset.id;wx.navigateTo({url:'/pages/moment/detail/index?id='+id})},createMoment(){wx.navigateTo({url:'/pages/moment/editor/index?chapterId='+this.data.id})},openMembers(){wx.navigateTo({url:'/pages/chapter/members/index?id='+this.data.id})},openReview(){wx.navigateTo({url:'/pages/review/index?id='+this.data.id})},edit(){wx.navigateTo({url:'/pages/chapter/editor/index?id='+this.data.id})},heroImageError(){this.setData({coverFailed:true})},filterMine(){this.setData({filter:this.data.filter==='all'?'mine':'all'});this.load()},openCalendar(){this.setData({activeTab:'日历',calendar:store.getCalendarData(this.data.id)})},closeCalendar(){this.setData({showCalendar:false})},previousMonth(){this.changeMonth(this.data.calendar.previousMonthKey)},nextMonth(){this.changeMonth(this.data.calendar.nextMonthKey)},changeMonth(month){this.setData({calendar:store.getCalendarData(this.data.id,month,'')})},selectDay(e){const key=e.currentTarget.dataset.key;this.setData({calendar:store.getCalendarData(this.data.id,key.slice(0,7),key)})},recordSelectedDay(){wx.navigateTo({url:'/pages/moment/editor/index?chapterId='+this.data.id+'&date='+this.data.calendar.selectedDateKey})},selectTab(e){this.setData({activeTab:e.currentTarget.dataset.tab})},
 toggleGoal(e){if(!this.data.chapter.isOwner)return;try{const result=store.toggleGoal(this.data.id,e.currentTarget.dataset.id);if(result)this.syncGoals()}catch(error){wx.showToast({title:error.message||'目标未保存',icon:'none'})}},
 openGoal(e){if(!this.data.chapter.isOwner)return;const goal=(this.data.chapter.goals||[]).find(x=>x.id===e.currentTarget.dataset.id);this.setData({goalPanel:true,goalId:goal?goal.id:'',goalTitle:goal?goal.title:'',goalError:''})},
 closeGoal(){this.setData({goalPanel:false})},inputGoal(e){this.setData({goalTitle:e.detail.value})},
 saveGoal(){if(!this.data.chapter.isOwner)return;const title=this.data.goalTitle.trim();if(!title)return this.setData({goalError:'给这个目标写个名字'});try{const result=store.saveGoal(this.data.id,{id:this.data.goalId||undefined,title});if(!result||!this.syncGoals())return this.setData({goalError:store.getLastError()||'暂时无法保存'});this.setData({goalPanel:false})}catch(error){this.setData({goalError:error.message||'目标未保存'})}},
 deleteGoal(){if(!this.data.chapter.isOwner)return;wx.showModal({title:'删除这个目标？',success:r=>{if(!r.confirm)return;try{if(store.deleteGoal(this.data.id,this.data.goalId)&&this.syncGoals())this.setData({goalPanel:false})}catch(error){this.setData({goalError:error.message||'目标未删除'})}}})},
 syncGoals(){const current=store.getChapter(this.data.id);if(!current||!current.isOwner)return false;const result=store.saveChapter({id:current.id,goals:current.goals});if(!result)return false;cloud.flush();this.load();return true},
 noop(){},more(){const c=this.data.chapter;const actions=c.isOwner?['编辑 Chapter',c.status==='ONGOING'?'结束 Chapter':'恢复为进行中','删除 Chapter']:['查看成员','退出 Chapter'];wx.showActionSheet({itemList:actions,success:({tapIndex})=>{if(!c.isOwner){if(tapIndex===0)this.openMembers();else this.leave();return}if(tapIndex===0)this.edit();if(tapIndex===1){if(c.status==='ONGOING')wx.navigateTo({url:'/pages/review/index?id='+c.id+'&finish=1'});else{store.setChapterStatus(c.id,'ONGOING');if(cloud.flush)cloud.flush();this.load()}}if(tapIndex===2)wx.showModal({title:'删除这个 Chapter？',content:'其中的记录和共同视角也会删除。',confirmText:'删除',confirmColor:'#b73336',success:r=>{if(r.confirm){const ok=store.deleteChapter(c.id);if(!ok)return wx.showToast({title:store.getLastError()||'无法删除',icon:'none'});if(cloud.flush)cloud.flush();wx.navigateBack({fail:()=>wx.redirectTo({url:'/pages/history/index'})})}}})}})},leave(){wx.showModal({title:'退出这个 Chapter？',content:'已经分享的记录将保留在章节中。',success:r=>{if(r.confirm){cloud.removeMember(this.data.id,store.getCurrentUser().id).then(ok=>{if(ok){store.removeMember(this.data.id,store.getCurrentUser().id);wx.redirectTo({url:'/pages/index/index'})}else wx.showToast({title:'退出失败，请重试',icon:'none'})})}}})},goBack(){wx.navigateBack({fail:()=>wx.redirectTo({url:'/pages/history/index'})})}})
