const IMG=n=>`assets/images/${n}`;
const seed={
 users:[
  {id:'user-owner',nickname:'夏天的记录者',avatar:IMG('chapter-summer.webp')},
  {id:'user-lin',nickname:'林一',avatar:IMG('summer-friends.webp')},
  {id:'user-chen',nickname:'陈昼',avatar:IMG('quiet-reading.webp')}
 ],
 chapters:[
  {id:'summer-2026',title:'大二暑假',englishTitle:'SUMMER 2026',status:'ONGOING',startDate:'2026-07-01',endDate:'2026-09-20',description:'在出发与停留之间，长成更喜欢的样子。',cover:IMG('chapter-summer.webp'),memberIds:['user-owner','user-lin','user-chen'],ending:'这一章，写完了。'},
  {id:'qingdao-trip',title:'青岛三日',englishTitle:'A SHORT ESCAPE',status:'COMPLETED',startDate:'2026-05-02',endDate:'2026-05-04',description:'三天很短，海风记得我们走过的路。',cover:IMG('island-road.webp'),memberIds:['user-owner','user-lin'],ending:'这一章，写完了。海风会替我们记得。'},
  {id:'photo-practice',title:'胶片练习',englishTitle:'LIGHT STUDIES',status:'ARCHIVED',startDate:'2026-03-01',endDate:'2026-04-15',description:'慢一点看光，也慢一点看生活。',cover:IMG('reading-window.webp'),memberIds:['user-owner'],ending:''}
 ],
 moments:[
  {id:'m01',chapterId:'summer-2026',creatorId:'user-owner',content:'傍晚的海风很温柔，和好朋友一起看了日落。原来快乐可以这么简单。',location:'青岛 · 小麦岛',tags:['朋友','日落'],mood:'开心',image:IMG('moment-sunset.webp'),createdAt:'2026-09-07T18:42:00',favorite:true},
  {id:'m02',chapterId:'summer-2026',creatorId:'user-chen',content:'给自己留了一个没有安排的上午，光落在纸上，时间也变得很慢。',location:'家里的窗边',tags:['独处','阅读'],mood:'平静',image:IMG('reading-window.webp'),createdAt:'2026-09-06T10:16:00'},
  {id:'m03',chapterId:'summer-2026',creatorId:'user-owner',content:'第一次把想了很久的页面真正做出来。小小的完成，也值得被记住。',location:'学校图书馆',tags:['学习','里程碑'],mood:'兴奋',image:IMG('moment-study.webp'),createdAt:'2026-09-06T20:08:00'},
  {id:'m04',chapterId:'summer-2026',creatorId:'user-lin',content:'绕远路去买冰饮，意外看见一整片金色的云。',location:'沿海公路',tags:['晚霞','散步'],mood:'期待',image:IMG('coastal-road.webp'),createdAt:'2026-09-05T17:30:00'},
  {id:'m06',chapterId:'summer-2026',creatorId:'user-owner',content:'和妈妈一起学做了番茄牛腩，味道比想象中更好。',location:'家',tags:['家人','美食'],mood:'开心',image:IMG('home-cooking.webp'),createdAt:'2026-09-03T12:02:00'},
  {id:'m07',chapterId:'summer-2026',creatorId:'user-lin',content:'海边走了很久，最后谁也没有急着回去。',location:'石老人海水浴场',tags:['朋友','散步'],mood:'放松',image:IMG('beach-walk.webp'),createdAt:'2026-09-02T18:10:00'},
  {id:'m08',chapterId:'summer-2026',creatorId:'user-owner',content:'天刚亮时的海是安静的蓝。第一次完整看完日出。',location:'海边',tags:['日出'],mood:'兴奋',image:IMG('sunlit-book.webp'),createdAt:'2026-09-01T06:10:00'},
  {id:'q01',chapterId:'qingdao-trip',creatorId:'user-owner',content:'第一眼看见海，旅程真正开始了。',location:'青岛站',tags:['旅行'],mood:'期待',image:IMG('island-road.webp'),createdAt:'2026-05-02T10:20:00'},
  {id:'q02',chapterId:'qingdao-trip',creatorId:'user-lin',content:'风很大，但我们还是在栈桥停了很久。',location:'栈桥',tags:['朋友','旅行'],mood:'开心',image:IMG('summer-friends.webp'),createdAt:'2026-05-03T16:40:00'},
  {id:'q03',chapterId:'qingdao-trip',creatorId:'user-owner',content:'最后一晚，把想说的话都留在了海边。',location:'小麦岛',tags:['告别'],mood:'平静',image:IMG('moment-sunset.webp'),createdAt:'2026-05-04T20:35:00'}
 ],
 contributions:[
  {id:'c1',momentId:'m01',creatorId:'user-lin',content:'我记得那天我们一直坐到天完全暗下来。',createdAt:'2026-09-07T21:04:00'},
  {id:'c2',momentId:'m01',creatorId:'user-chen',content:'这是我相机里的另一个角度。',image:IMG('summer-friends.webp'),createdAt:'2026-09-07T21:20:00'},
  {id:'c3',momentId:'m03',creatorId:'user-lin',content:'那天你说终于敢把想法做出来了。',createdAt:'2026-09-06T22:10:00'}
 ],
 activeChapterId:'summer-2026',currentUserId:'user-owner'
};

const KEY='ongoing:web-demo:v2';
let state=load();let route={view:'home'};let selectedDate='2026-09-07';
function clone(o){return JSON.parse(JSON.stringify(o))}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||clone(seed)}catch(e){return clone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function reset(){state=clone(seed);save();route={view:'home'};render();toast('Demo 数据已重置')}
function user(id){return state.users.find(x=>x.id===id)||state.users[0]}
function chapter(id){return state.chapters.find(x=>x.id===id)}
function chapterMoments(id){return state.moments.filter(x=>x.chapterId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
function currentChapter(){return chapter(state.activeChapterId)||state.chapters[0]}
function fmtDate(s){const d=new Date(s);return `${d.getMonth()+1}月${d.getDate()}日`}
function dateKey(s){return s.slice(0,10)}
function go(view,id){route={view,id};window.scrollTo({top:0,behavior:'smooth'});render()}
function back(){if(route.view==='moment')go('chapter',state.moments.find(m=>m.id===route.id)?.chapterId||state.activeChapterId);else go('home')}
function shell(content,{backButton=false,title='ongoing_',tab='now'}={}){return `<div class="phone-shell"><header class="topbar">${backButton?`<button class="back-btn" onclick="back()">‹</button>`:''}<div class="brand">${title}<span class="demo-badge">WEB DEMO</span></div><button class="icon-btn" onclick="openAbout()">•••</button></header>${content}${tabbar(tab)}<div id="toast" class="toast"></div></div>`}
function tabbar(active){return `<nav class="tabbar"><button class="tab ${active==='now'?'active':''}" onclick="go('home')"><b>⌂</b>当下</button><button class="tab ${active==='chapters'?'active':''}" onclick="go('chapters')"><b>▤</b>章节</button><button class="tab add" onclick="openComposer()">＋</button><button class="tab ${active==='review'?'active':''}" onclick="go('review',state.activeChapterId)"><b>◫</b>回望</button><button class="tab" onclick="openAbout()"><b>○</b>我的</button></nav>`}
function imageTag(src,alt=''){return src?`<img src="${src}" alt="${alt}" onerror="this.style.opacity=.15">`:''}

function home(){const ch=currentChapter();const ms=chapterMoments(ch.id);const today=ms[0]?.createdAt||new Date().toISOString();const d=new Date(today);const recent=ms.slice(0,4);const chapters=state.chapters.filter(c=>c.status==='ONGOING');return shell(`<main class="page"><section><div class="today-lockup"><div class="day">${String(d.getDate()).padStart(2,'0')}</div><div class="date-aside">${d.getMonth()+1}月<br>星期${'日一二三四五六'[d.getDay()]} · 今天</div></div><h1 class="today-title">今天，有什么想留给<br><span class="accent">以后的自己？</span></h1></section><button class="record-card" onclick="openComposer()"><div><span class="palette-dots"><i></i><i></i><i></i></span><span class="capture-title">记录此刻</span><span class="capture-caption">文字 · 照片 · 声音</span></div><div class="capture-plus">＋</div></button><div class="section-head"><div><div class="section-title">最近的 Moment</div><div class="section-caption">生活的小切片</div></div><button class="text-link" onclick="go('chapter','${ch.id}')">查看全部 ›</button></div><div class="horizontal">${recent.map(momentCard).join('')}</div>${recent[0]?`<button class="echo-card" onclick="go('moment','${recent[0].id}')">${imageTag(recent[0].image,'Memory Echo')}<div class="echo-veil"></div><div class="echo-copy"><div class="echo-label">时间来信 · Memory Echo</div><div class="echo-title">${fmtDate(recent[0].createdAt)}的这一刻</div><div class="echo-excerpt">${recent[0].content}</div></div></button>`:''}<div class="section-head"><div><div class="section-title">正在经历</div><div class="section-caption">Chapter · 一段生活</div></div></div><div class="horizontal">${chapters.map(chapterCard).join('')}</div><div class="colophon">此刻很轻，时间会记得。</div></main>`,{tab:'now'})}
function momentCard(m){return `<article class="moment-card" onclick="go('moment','${m.id}')">${imageTag(m.image,m.content)}<div class="moment-card-body"><div class="moment-meta">${fmtDate(m.createdAt)} · ${user(m.creatorId).nickname}</div><div class="moment-copy">${m.content}</div><div class="moment-foot"><span>${m.location||'未记录地点'}</span><span>${m.mood||''}</span></div></div></article>`}
function chapterCard(c){const ms=chapterMoments(c.id);return `<button class="chapter-card" onclick="go('chapter','${c.id}')"><div><div class="chapter-time">${c.status==='ONGOING'?'正在发生':'已成章'}</div><div class="chapter-title">${c.title}</div><div class="chapter-meta">${c.startDate} — ${c.endDate}<br>${ms.length} Moment · ${new Set(ms.map(x=>dateKey(x.createdAt))).size} 个记录日</div><div class="member-row">${c.memberIds.map(id=>`<img class="member-avatar" src="${user(id).avatar}">`).join('')}</div></div>${imageTag(c.cover,c.title).replace('<img','<img class="chapter-cover"')}</button>`}

function chapterView(id){const c=chapter(id)||currentChapter();const ms=chapterMoments(c.id);const days=new Set(ms.map(x=>dateKey(x.createdAt))).size;return shell(`<main class="page"><section class="hero-cover">${imageTag(c.cover,c.title)}<div class="hero-copy"><div class="eyebrow">${c.englishTitle}</div><h1>${c.title}</h1><div>${c.description}</div></div></section><div class="stats"><div class="stat"><strong>${ms.length}</strong><span>Moment</span></div><div class="stat"><strong>${days}</strong><span>记录日</span></div><div class="stat"><strong>${c.memberIds.length}</strong><span>成员</span></div></div><div class="segmented"><button class="active">瞬间</button><button onclick="go('calendar','${c.id}')">日历</button><button onclick="go('review','${c.id}')">回望</button></div><div class="section-head"><div class="section-title">瞬间</div><button class="text-link" onclick="openComposer('${c.id}')">＋ 记录</button></div><div class="feed">${ms.map(feedItem).join('')}</div></main>`,{backButton:true,title:c.title,tab:'chapters'})}
function feedItem(m){return `<article class="feed-item" onclick="go('moment','${m.id}')">${m.image?imageTag(m.image,m.content):'<div></div>'}<div><div class="feed-meta">${fmtDate(m.createdAt)} · ${user(m.creatorId).nickname}</div><div class="feed-copy">${m.content}</div><div class="chips">${(m.tags||[]).map(t=>`<span class="chip"># ${t}</span>`).join('')}</div></div></article>`}
function chaptersView(){return shell(`<main class="page"><div class="section-head"><div><div class="section-title">Chapter</div><div class="section-caption">正在发生 / 已成章 / 已归档</div></div></div><div class="feed">${state.chapters.map(c=>`<div>${chapterCard(c)}</div>`).join('')}</div></main>`,{tab:'chapters'})}

function momentView(id){const m=state.moments.find(x=>x.id===id);if(!m)return home();const cs=state.contributions.filter(x=>x.momentId===id);return shell(`<main class="page">${m.image?`<div class="detail-media">${imageTag(m.image,m.content)}</div>`:''}<div class="detail-copy">${m.content}</div><div class="detail-info"><div>◷ ${new Date(m.createdAt).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})}</div><div>⌖ ${m.location||'没有留下地点'}</div><div>☺ ${m.mood||'没有记录心情'}</div></div><div class="chips">${(m.tags||[]).map(t=>`<span class="chip"># ${t}</span>`).join('')}</div><section class="contrib"><div class="section-head"><div><div class="section-title">共同视角</div><div class="section-caption">${cs.length} 条补完</div></div><button class="text-link" onclick="openContribution('${m.id}')">邀请补完 ＋</button></div>${cs.length?cs.map(c=>`<div class="contrib-card"><div class="contrib-author">${user(c.creatorId).nickname} · ${fmtDate(c.createdAt)}</div><div>${c.content}</div>${c.image?imageTag(c.image,c.content):''}</div>`).join(''):'<div class="empty">这一刻还没有朋友补完。</div>'}</section></main>`,{backButton:true,title:'Moment',tab:'now'})}

function calendarView(id){const c=chapter(id)||currentChapter();const ms=chapterMoments(c.id);const ym='2026-09';const first=new Date(2026,8,1).getDay();const days=30;let cells='';for(let i=0;i<first;i++)cells+='<div class="day-cell blank"></div>';for(let n=1;n<=days;n++){const key=`${ym}-${String(n).padStart(2,'0')}`;const has=ms.some(m=>dateKey(m.createdAt)===key);cells+=`<button class="day-cell ${has?'has':''} ${selectedDate===key?'selected':''}" onclick="selectDate('${key}','${c.id}')">${n}</button>`}const sel=ms.filter(m=>dateKey(m.createdAt)===selectedDate);return shell(`<main class="page"><div class="calendar-head"><div><div class="eyebrow">Calendar</div><h2>2026 · 09</h2></div><div class="muted">${c.title}</div></div><div class="calendar"><div class="weekdays">${['日','一','二','三','四','五','六'].map(x=>`<span>${x}</span>`).join('')}</div><div class="days">${cells}</div></div><div class="day-feed"><div class="section-head"><div><div class="section-title">${selectedDate.slice(5).replace('-','月')}日</div><div class="section-caption">${sel.length} 个 Moment</div></div></div><div class="feed">${sel.length?sel.map(feedItem).join(''):'<div class="empty">这一天没有留下 Moment。点亮有圆点的日期试试。</div>'}</div></div></main>`,{backButton:true,title:'日历',tab:'chapters'})}
function selectDate(key,id){selectedDate=key;go('calendar',id)}

function reviewView(id){const c=chapter(id)||currentChapter();const ms=chapterMoments(c.id);const days=new Set(ms.map(x=>dateKey(x.createdAt))).size;const locations=new Set(ms.map(x=>x.location).filter(Boolean)).size;const contribs=state.contributions.filter(x=>ms.some(m=>m.id===x.momentId)).length;const timeline=ms.slice().reverse();return shell(`<main class="page"><section class="review-hero"><div class="review-kicker">${c.englishTitle} · REVIEW</div><h1>${c.title}</h1><div class="review-quote">${c.ending||'这一章，还在继续。'}<br>${c.description}</div></section><div class="review-grid"><div class="review-card"><strong>${ms.length}</strong><span class="muted">Moment</span></div><div class="review-card"><strong>${days}</strong><span class="muted">记录日</span></div><div class="review-card"><strong>${c.memberIds.length}</strong><span class="muted">共同成员</span></div><div class="review-card"><strong>${locations}</strong><span class="muted">留下地点</span></div></div><div class="notice">Web Demo 会保留你在当前浏览器中的新增记录；它用于体验核心产品流程，不模拟真实微信跨设备同步。</div><div class="section-head"><div><div class="section-title">完整时间线</div><div class="section-caption">${contribs} 条共同补完</div></div></div><div class="timeline">${timeline.map(m=>`<div class="timeline-item"><div class="timeline-date">${fmtDate(m.createdAt)}</div><div class="timeline-copy">${m.content}</div></div>`).join('')}</div><div style="height:22px"></div><button class="secondary-btn" onclick="toast('海报生成在微信小程序正式版中提供')">生成回望海报</button></main>`,{backButton:true,title:'回望',tab:'review'})}

function openComposer(chapterId=state.activeChapterId){const mask=document.createElement('div');mask.className='modal-mask';mask.id='modal';mask.innerHTML=`<div class="sheet"><h3>记录此刻</h3><p>低成本留下一个 Moment，其他信息以后也可以补。</p><div class="form"><div class="field"><label>一句话</label><textarea id="m-content" placeholder="现在发生了什么？"></textarea></div><div class="field"><label>地点</label><input id="m-location" placeholder="例如：青岛 · 小麦岛"></div><div class="field"><label>标签</label><input id="m-tags" placeholder="朋友, 日落"></div><button class="primary-btn" onclick="saveMoment('${chapterId}')">保存 Moment</button><button class="secondary-btn" onclick="closeModal()">取消</button></div></div>`;document.body.appendChild(mask)}
function saveMoment(chapterId){const content=document.getElementById('m-content').value.trim();if(!content)return toast('先写下一句话');const now=new Date();const id='web-'+Date.now();state.moments.push({id,chapterId,creatorId:state.currentUserId,content,location:document.getElementById('m-location').value.trim(),tags:document.getElementById('m-tags').value.split(/[,，]/).map(s=>s.trim()).filter(Boolean),mood:'',image:'',createdAt:now.toISOString()});save();closeModal();toast('这一刻，已经留下');setTimeout(()=>go('moment',id),250)}
function openContribution(momentId){const mask=document.createElement('div');mask.className='modal-mask';mask.id='modal';mask.innerHTML=`<div class="sheet"><h3>补完这一刻</h3><p>Web Demo 用“林一”的身份模拟另一位 Chapter 成员。</p><div class="form"><div class="field"><label>林一记得的内容</label><textarea id="c-content" placeholder="我记得……"></textarea></div><button class="primary-btn" onclick="saveContribution('${momentId}')">加入共同视角</button><button class="secondary-btn" onclick="closeModal()">取消</button></div></div>`;document.body.appendChild(mask)}
function saveContribution(momentId){const content=document.getElementById('c-content').value.trim();if(!content)return toast('写下一点不同的记忆');state.contributions.push({id:'web-c-'+Date.now(),momentId,creatorId:'user-lin',content,createdAt:new Date().toISOString()});save();closeModal();render();toast('共同视角已补完')}
function openAbout(){const mask=document.createElement('div');mask.className='modal-mask';mask.id='modal';mask.innerHTML=`<div class="sheet"><h3>ongoing_ / 未完</h3><p>这是原生微信小程序的课程 Web Demo。它复刻 Chapter、Moment、Calendar、Contribution 和 Review 核心流程，数据保存在当前浏览器。</p><div class="form"><button class="secondary-btn" onclick="reset();closeModal()">重置 Demo 数据</button><button class="primary-btn" onclick="closeModal()">继续体验</button></div></div>`;document.body.appendChild(mask)}
function closeModal(){document.getElementById('modal')?.remove()}
function toast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}
function render(){const app=document.getElementById('app');if(route.view==='home')app.innerHTML=home();else if(route.view==='chapter')app.innerHTML=chapterView(route.id);else if(route.view==='chapters')app.innerHTML=chaptersView();else if(route.view==='moment')app.innerHTML=momentView(route.id);else if(route.view==='calendar')app.innerHTML=calendarView(route.id);else if(route.view==='review')app.innerHTML=reviewView(route.id);else app.innerHTML=home()}
window.go=go;window.back=back;window.openComposer=openComposer;window.saveMoment=saveMoment;window.openContribution=openContribution;window.saveContribution=saveContribution;window.openAbout=openAbout;window.closeModal=closeModal;window.reset=reset;window.selectDate=selectDate;window.toast=toast;window.state=state;
render();
