const assert=require('node:assert/strict')
const clone=x=>x==null?x:JSON.parse(JSON.stringify(x))
let memory={},writes=0,failWrite=false,removed=[]
global.wx={getStorageSync:k=>clone(memory[k]),setStorageSync(k,v){if(failWrite)throw Error('full');memory[k]=clone(v);writes++},removeSavedFile(o){removed.push(o.filePath)}}
const store=require('../services/store')
const fresh=()=>{memory={};store.init();return store.getCurrentUser().id}
const actor=fresh()
assert.equal(store.getChapters().length,0,'首次安装没有示例内容')
assert.equal(store.getMoments().length,0)
let before=writes;store.getState();store.getChapters();assert.equal(writes,before,'读取不写缓存')
const legacy={schemaVersion:2,currentUserId:'owner',users:[{id:'owner',nickname:'我'}],chapters:[{id:'old',ownerId:'owner',memberIds:['owner'],title:'旧章节',goals:[{id:'g',title:'历史目标'}]}],moments:[{id:'old-m',chapterId:'old',creatorId:'owner',content:'旧记录',createdAt:'2024-07-18T23:00:00+08:00'}],contributions:[],invites:[]}
memory={'ongoing:data:v2':clone(legacy)};store.init()
assert.deepEqual(memory['ongoing:backup:before-v3'],legacy)
assert.equal(store.getState().schemaVersion,3);assert.equal(store.getChapter('old').goals[0].title,'历史目标')
assert.equal(store.getMoment('old-m').localDateKey,'2024-07-18')
const me=fresh()
const a=store.saveChapter({title:'东京交换'}),b=store.saveChapter({title:'第一次实习'})
assert.equal(store.getChapters('ONGOING').length,2)
assert.equal(a.cover,'')
const mixed=store.saveMoment({chapterId:a.id,content:'一整天',media:[{id:'p',type:'image',path:'/saved/p.jpg'}],voicePath:'/saved/a.mp3',voiceDuration:8,location:'车站'})
assert.equal(mixed.media.length,1);assert.ok(mixed.voicePath)
assert.ok(store.saveMoment({type:'text',media:[{id:'p2',type:'image',path:'/saved/p2.jpg'}]}),'照片无需先选类型')
assert.equal(store.saveMoment({content:'  '}),null)
const unfiled=store.saveMoment({content:'先记下来'});assert.equal(unfiled.chapterId,'');assert.ok(store.getMoments().some(m=>m.id===unfiled.id))
store.saveEditorDraft(me+':new',{content:'未提交的草稿'})
const draft=store.saveMoment({chapterId:a.id,status:'DRAFT',content:'草稿地点',location:'隐藏地点'})
assert.ok(!store.getReviewData(a.id).moments.some(m=>m.id===draft.id))
assert.ok(!store.getCalendarData(a.id).selectedMoments.some(m=>m.id===draft.id))
assert.equal(store.search('隐藏地点').places.length,0)
assert.ok(!store.exportChapterSnapshot(a.id).moments.some(m=>m.id===draft.id))
const state=store.getState();state.users.push({id:'guest',nickname:'朋友'});state.chapters.find(c=>c.id===a.id).memberIds.push('guest');store.setState(state);store.setCurrentUser('guest')
assert.equal(store.getMoment(draft.id),null)
const perspective=store.saveContribution({momentId:mixed.id,content:'我看到的',voicePath:'/saved/g.mp3'})
assert.ok(perspective)
store.setCurrentUser(me)
assert.equal(store.saveContribution({id:perspective.id,momentId:mixed.id,content:'覆盖他人'}),null)
assert.equal(store.deleteContribution(perspective.id),false)
assert.equal(store.getPerspectives(mixed.id).length,2)
assert.equal(store.saveMoment({id:mixed.id,chapterId:b.id,content:'改归属'}),null,'共同记录不可随意改变访问范围')
store.completeChapter(a.id,'');assert.ok(store.saveMoment({chapterId:a.id,content:'后来补记'}))
const end=store.getChapter(a.id).endDate;store.completeChapter(a.id,'结语');assert.equal(store.getChapter(a.id).endDate,end)
store.setChapterStatus(a.id,'ONGOING');assert.equal(store.getChapter(a.id).endDate,'')
const local=store.saveMoment({chapterId:b.id,content:'尚未同步'})
store.mergeSharedSnapshot({chapter:store.getChapter(b.id),moments:[],contributions:[]})
assert.equal(store.getMoment(local.id).content,'尚未同步')
const operation=store.getPendingOps().find(op=>op.id===local.id)
store.saveMoment({id:local.id,content:'同步时又编辑'})
store.acknowledgeOperation(operation,{id:local.id,content:'尚未同步',serverVersion:1})
assert.equal(store.getMoment(local.id).content,'同步时又编辑')
assert.equal(store.getPendingOps().find(op=>op.id===local.id).data.moment.serverVersion,1)
before=store.getMoments().length;failWrite=true
assert.equal(store.saveMoment({content:'存储已满'}),null);assert.equal(store.getMoments().length,before);assert.match(store.getLastError(),/存储/)
const removedBefore=removed.length;assert.equal(store.deleteMoment(mixed.id),null);assert.equal(removed.length,removedBefore,'写入失败不先删媒体');assert.ok(store.getMoment(mixed.id));failWrite=false
assert.equal(store.deleteMoment(local.id),true);assert.ok(store.getState().deletedIds.includes(local.id));assert.ok(!store.getPendingOps().some(op=>op.id===local.id&&op.action==='saveMoment'))
store.mergeSharedSnapshot({chapter:store.getChapter(b.id),moments:[{id:local.id,creatorId:me,chapterId:b.id,content:'远端旧快照'}]});assert.equal(store.getMoment(local.id),null)
store.adoptIdentity({id:'openid',nickname:'本人'});assert.ok(store.getEditorDraft('openid:new'));assert.ok(store.getPendingOps().filter(op=>op.action==='saveChapter').every(op=>op.data.chapter.ownerId==='openid'))
const single=store.saveMoment({content:'邀请一个人'});const shared=store.getState();shared.moments.find(m=>m.id===single.id).participantIds=['guest'];store.setState(shared);store.setCurrentUser('guest');assert.ok(store.getMoment(single.id));assert.equal(store.getChapter(b.id),null);assert.ok(store.saveContribution({momentId:single.id,content:'只参与这一条'}))
store.revokeAccess('moment',single.id);assert.equal(store.getMoment(single.id),null)
store.setCurrentUser('openid');const c=store.saveChapter({title:'很多记录'});for(let i=0;i<205;i++)assert.ok(store.saveMoment({chapterId:c.id,content:'记录 '+i,localDateKey:'2026-09-01'}))
assert.equal(store.getReviewData(c.id).moments.length,205);assert.equal(store.getCalendarData(c.id,'2026-09','2026-09-01').selectedMomentCount,205)
const read=wx.getStorageSync;wx.getStorageSync=()=>{throw Error('read failure')};before=writes;assert.throws(()=>store.init(),/现有记录未被覆盖/);assert.equal(writes,before);wx.getStorageSync=read
console.log('archive behavior passed: migration, mixed media, drafts, permissions, late entries, offline writes, sync races, tombstones, 205 records')
