const assert=require('node:assert/strict')
const vm=require('node:vm')
const fs=require('node:fs')
const rows={};let user='owner';let fileRequests=[]
const copy=x=>JSON.parse(JSON.stringify(x))
const matches=(row,query)=>Object.entries(query).every(([k,v])=>v&&v.op==='exists'?((row[k]!==undefined)===v.value):Array.isArray(row[k])?row[k].includes(v):row[k]===v)
function collection(name){rows[name]=rows[name]||[];return {where(query){return queryFor(name,query)},doc(id){return{async update({data}){const target=rows[name].find(r=>r._id===id);if(!target)throw Error('missing');apply(target,data);return{stats:{updated:1}}}}},async add({data}){if(rows[name].some(r=>r._id===data._id))throw Error('duplicate');rows[name].push(copy(data));return{_id:data._id}}}}
function apply(row,values){for(const [key,value]of Object.entries(values)){if(value&&value.op==='add')row[key]=Array.from(new Set((row[key]||[]).concat(value.value)));else if(value&&value.op==='pull')row[key]=(row[key]||[]).filter(x=>x!==value.value);else row[key]=copy(value)}}
function queryFor(name,query){let offset=0,limit=100;const q={limit(n){limit=n;return q},skip(n){offset=n;return q},orderBy(){return q},async get(){return{data:copy(rows[name].filter(r=>matches(r,query)).slice(offset,offset+limit))}},async update({data}){const selected=rows[name].filter(r=>matches(r,query));selected.forEach(row=>apply(row,data));return{stats:{updated:selected.length}}}};return q}
const sdk={DYNAMIC_CURRENT_ENV:'test',init(){},database:()=>({collection,command:{exists:value=>({op:'exists',value}),addToSet:value=>({op:'add',value}),pull:value=>({op:'pull',value})}}),getWXContext:()=>({OPENID:user}),async getTempFileURL({fileList}){fileRequests.push(...fileList.map(f=>f.fileID));return{fileList:fileList.map(f=>({fileID:f.fileID,tempFileURL:'https://signed.test/'+f.fileID}))}}}
const sandbox={exports:{},require:name=>name==='wx-server-sdk'?sdk:require(name),console};vm.runInNewContext(fs.readFileSync(require.resolve('../cloudfunctions/collaboration/index.js'),'utf8'),sandbox)
const run=async(action,data={})=>sandbox.exports.main(Object.assign({action},data))
const ok=async(action,data)=>{const r=await run(action,data);assert.equal(r.ok,true,r.error);return r.data}
;(async()=>{
 await ok('ensureUser',{profile:{nickname:'本人'}})
 const chapter=await ok('saveChapter',{chapter:{id:'c',title:'交换',status:'ONGOING',memberIds:['stranger']},operationId:'c1'})
 assert.deepEqual(Array.from(chapter.memberIds),['owner'],'客户端不能自己给其他人授权')
 const original=await ok('saveMoment',{moment:{id:'m',chapterId:'c',content:'私密记录',media:[{id:'p',type:'image',path:'cloud://private/photo'}]},operationId:'m1'})
 const invite=await ok('createInvite',{scope:'moment',momentId:'m'})
 assert.equal(invite.code.length,48)
 user='guest';await ok('ensureUser',{profile:{nickname:'朋友'}})
 const preview=await ok('peekInvite',{code:invite.code});assert.equal(preview.scope,'moment');assert.equal(preview.content,undefined)
 assert.equal((await run('getMoment',{momentId:'m'})).error,'NO_ACCESS')
 const joined=await ok('joinInvite',{code:invite.code});assert.equal(joined.chapter,undefined);assert.equal(joined.moment.id,'m');assert.ok(joined.mediaUrls['cloud://private/photo'])
 assert.equal((await run('getChapter',{chapterId:'c'})).error,'NOT_A_MEMBER')
 assert.ok(!rows.ongoing_chapters[0].memberIds.includes('guest'))
 const perspective=await ok('saveContribution',{contribution:{id:'g1',momentId:'m',content:'我的视角'},operationId:'g1op'})
 user='attacker';assert.equal((await run('saveContribution',{contribution:{id:'g1',momentId:'m',content:'覆盖'},operationId:'attack'})).ok,false)
 user='owner';assert.equal((await run('saveContribution',{contribution:{id:'g1',momentId:'m',content:'覆盖'},operationId:'attack2'})).error,'CREATOR_ONLY')
 assert.equal((await run('saveMoment',{moment:{id:'draft',chapterId:'c',status:'DRAFT',content:'草稿'},operationId:'draft'})).error,'DRAFT_PRIVATE')
 rows.ongoing_moments.push({_id:'legacy-draft',id:'legacy-draft',chapterId:'c',creatorId:'owner',status:'DRAFT',content:'旧草稿'})
 const memberInvite=await ok('createInvite',{scope:'chapter',chapterId:'c'});user='member';await ok('joinInvite',{code:memberInvite.code})
 assert.ok(!(await ok('getChapter',{chapterId:'c'})).moments.some(m=>m.id==='legacy-draft'))
 assert.equal((await run('saveMoment',{moment:{id:'m',chapterId:'c',content:'覆盖他人'},operationId:'bad'})).error,'CREATOR_ONLY')
 user='owner';const v2=await ok('saveMoment',{moment:{id:'m',chapterId:'c',content:'更新内容',serverVersion:1},operationId:'m2'})
 assert.equal(v2.serverVersion,2)
 assert.equal((await ok('saveMoment',{moment:{id:'m',chapterId:'c',content:'更新内容',serverVersion:1},operationId:'m2'})).serverVersion,2,'重试幂等')
 assert.equal((await run('saveMoment',{moment:{id:'m',chapterId:'c',content:'旧设备',serverVersion:1},operationId:'old'})).error,'CONFLICT')
 assert.ok(v2.participantIds.includes('guest'),'内容修改不会覆盖成员列表')
 await ok('removeMember',{chapterId:'c',memberId:'member'});user='member';assert.equal((await run('getChapter',{chapterId:'c'})).error,'NOT_A_MEMBER');user='guest';assert.ok(await ok('getMoment',{momentId:'m'}),'整章移除不影响明确的单条授权')
 user='owner';const standalone=await ok('saveMoment',{moment:{id:'solo',chapterId:'',content:'稍后归入'},operationId:'solo1'});assert.equal((await ok('saveMoment',{moment:{id:'solo',chapterId:'c',content:'现在归入',serverVersion:1},operationId:'solo2'})).chapterId,'c')
 for(let i=0;i<205;i++)rows.ongoing_moments.push({_id:'large'+i,id:'large'+i,chapterId:'c',creatorId:'owner',content:'记录',status:'PUBLISHED'})
 assert.equal((await ok('getChapter',{chapterId:'c'})).moments.length,207,'服务端分页超过 100 条')
 await ok('deleteMoment',{momentId:'m'});assert.equal((await run('getMoment',{momentId:'m'})).error,'DELETED');assert.equal((await run('saveMoment',{moment:{id:'m',chapterId:'c',content:'复活',serverVersion:2},operationId:'resurrect'})).error,'DELETED')
 await ok('deleteChapter',{chapterId:'c'});assert.equal((await run('getMoment',{momentId:'solo'})).error,'DELETED')
 console.log('cloud permissions passed: scoped invites, ownership, draft isolation, signed media, version conflicts, idempotency, 207 records, tombstones')
})().catch(e=>{console.error(e);process.exitCode=1})
